language: java

jdk:
  - oraclejdk8

env:
  = RESOURCES=$TRAVIS_BUILD_DIR/src/test/resources
  - JWNL=$RESOURCES/jwnl_file_properties.xml
  - WORDNET=$RESOURCES/wordnet

before_script:
  - mkdir -p $WORDNET
  - curl http://wordnetcode.princeton.edu/wn3.1.dict.tar.gz | tar -xzv -C $WORDNET

install: 
  - pip install --pre github3.py --user

script: mvn clean install

cache:
  directories:
  - $HOME/.m2
