language: java

jdk:
  - oraclejdk8

env:
  = RESOURCES=$TRAVIS_BUILD_DIR/src/test/resources
  - JWNL=$RESOURCES/jwnl_file_properties.xml

before_script:
#  - curl http://wordnetcode.princeton.edu/wn3.1.dict.tar.gz | tar xvz
  - wget http://wordnetcode.princeton.edu/wn3.1.dict.tar.gz
  - mkdir -p $RESOURCES
  - tar -xzvf wn3.1.dict.tar.gz -C $RESOURCES

install: true

script: mvn clean install

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
      - a.toledo.uu.nl@gmail.com
    on_success: change
    on_failure: always
